// Centralized mock data — used by mock API wrappers in src/api/*.api.js

export const mockStations = [
  {
    id: 's_001',
    name: 'Connaught Place SuperCharger',
    description: 'Premium fast-charging hub in central Delhi.',
    address: {
      line1: 'Block A, Connaught Place',
      city: 'New Delhi',
      state: 'DL',
      country: 'India',
      postalCode: '110001',
    },
    location: { lat: 28.6315, lng: 77.2167 },
    rating: 4.7,
    operatingHours: '24/7',
    amenities: ['Cafe', 'Restroom', 'Wi-Fi', 'Lounge'],
    images: ['https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=1200&q=80'],
    chargers: [
      { id: 'c_001', ocppId: 'CP-001', type: 'DC', connectorType: 'CCS', powerKW: 150, pricePerKWh: 18, status: 'AVAILABLE' },
      { id: 'c_002', ocppId: 'CP-002', type: 'DC', connectorType: 'CHAdeMO', powerKW: 100, pricePerKWh: 16, status: 'OCCUPIED' },
      { id: 'c_003', ocppId: 'CP-003', type: 'AC', connectorType: 'Type2', powerKW: 22, pricePerKWh: 12, status: 'AVAILABLE' },
      { id: 'c_004', ocppId: 'CP-004', type: 'DC', connectorType: 'CCS', powerKW: 150, pricePerKWh: 18, status: 'RESERVED' },
    ],
  },
  {
    id: 's_002',
    name: 'Cyber Hub FastCharge',
    description: 'Conveniently located in Cyber Hub, Gurgaon — perfect for a quick top-up while you grab coffee.',
    address: {
      line1: 'Cyber Hub, DLF Cyber City',
      city: 'Gurugram',
      state: 'HR',
      country: 'India',
      postalCode: '122002',
    },
    location: { lat: 28.4951, lng: 77.0890 },
    rating: 4.5,
    operatingHours: '06:00 – 23:00',
    amenities: ['Cafe', 'Restroom', 'Shopping'],
    images: ['https://images.unsplash.com/photo-1620891549027-942faf26c0e9?w=1200&q=80'],
    chargers: [
      { id: 'c_005', ocppId: 'CP-005', type: 'DC', connectorType: 'CCS', powerKW: 60, pricePerKWh: 16, status: 'AVAILABLE' },
      { id: 'c_006', ocppId: 'CP-006', type: 'AC', connectorType: 'Type2', powerKW: 22, pricePerKWh: 11, status: 'AVAILABLE' },
    ],
  },
  {
    id: 's_003',
    name: 'Saket Mall ChargePoint',
    description: 'Mall parking lot DC fast chargers. Validate parking with charging receipt.',
    address: {
      line1: 'Select Citywalk, Saket',
      city: 'New Delhi',
      state: 'DL',
      country: 'India',
      postalCode: '110017',
    },
    location: { lat: 28.5286, lng: 77.2197 },
    rating: 4.3,
    operatingHours: '10:00 – 22:00',
    amenities: ['Mall', 'Food Court'],
    images: ['https://images.unsplash.com/photo-1633113213050-7869fb6e51ce?w=1200&q=80'],
    chargers: [
      { id: 'c_007', ocppId: 'CP-007', type: 'DC', connectorType: 'CCS', powerKW: 50, pricePerKWh: 15, status: 'OCCUPIED' },
      { id: 'c_008', ocppId: 'CP-008', type: 'DC', connectorType: 'CCS', powerKW: 50, pricePerKWh: 15, status: 'OCCUPIED' },
      { id: 'c_009', ocppId: 'CP-009', type: 'AC', connectorType: 'Type2', powerKW: 11, pricePerKWh: 10, status: 'AVAILABLE' },
    ],
  },
  {
    id: 's_004',
    name: 'Noida Sector 18 ChargeHub',
    description: 'Family-friendly station with cafe, ample parking, and 24×7 support.',
    address: {
      line1: 'Sector 18',
      city: 'Noida',
      state: 'UP',
      country: 'India',
      postalCode: '201301',
    },
    location: { lat: 28.5707, lng: 77.3260 },
    rating: 4.6,
    operatingHours: '24/7',
    amenities: ['Cafe', 'Wi-Fi', 'Restroom'],
    images: ['https://images.unsplash.com/photo-1606925797300-0b35e9d1794e?w=1200&q=80'],
    chargers: [
      { id: 'c_010', ocppId: 'CP-010', type: 'DC', connectorType: 'CCS', powerKW: 120, pricePerKWh: 17, status: 'AVAILABLE' },
      { id: 'c_011', ocppId: 'CP-011', type: 'DC', connectorType: 'CCS', powerKW: 120, pricePerKWh: 17, status: 'AVAILABLE' },
      { id: 'c_012', ocppId: 'CP-012', type: 'AC', connectorType: 'Type2', powerKW: 22, pricePerKWh: 12, status: 'RESERVED' },
    ],
  },
  {
    id: 's_005',
    name: 'Greater Kailash EV Point',
    description: 'Reliable AC charging in South Delhi for overnight stays.',
    address: {
      line1: 'M Block Market, GK-1',
      city: 'New Delhi',
      state: 'DL',
      country: 'India',
      postalCode: '110048',
    },
    location: { lat: 28.5436, lng: 77.2453 },
    rating: 4.2,
    operatingHours: '07:00 – 23:00',
    amenities: ['Restroom'],
    images: ['https://images.unsplash.com/photo-1586282391129-76a6df230234?w=1200&q=80'],
    chargers: [
      { id: 'c_013', ocppId: 'CP-013', type: 'AC', connectorType: 'Type2', powerKW: 7, pricePerKWh: 9, status: 'AVAILABLE' },
      { id: 'c_014', ocppId: 'CP-014', type: 'AC', connectorType: 'Type2', powerKW: 7, pricePerKWh: 9, status: 'OCCUPIED' },
    ],
  },
  {
    id: 's_006',
    name: 'IGI Airport T3 Express',
    description: 'High-power chargers at airport long-term parking.',
    address: {
      line1: 'Terminal 3, IGI Airport',
      city: 'New Delhi',
      state: 'DL',
      country: 'India',
      postalCode: '110037',
    },
    location: { lat: 28.5562, lng: 77.1000 },
    rating: 4.4,
    operatingHours: '24/7',
    amenities: ['Wi-Fi', 'Restroom', 'Lounge'],
    images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=80'],
    chargers: [
      { id: 'c_015', ocppId: 'CP-015', type: 'DC', connectorType: 'CCS', powerKW: 180, pricePerKWh: 20, status: 'AVAILABLE' },
      { id: 'c_016', ocppId: 'CP-016', type: 'DC', connectorType: 'CCS', powerKW: 180, pricePerKWh: 20, status: 'AVAILABLE' },
    ],
  },
]

export const mockBookings = [
  {
    id: 'b_001',
    stationId: 's_001',
    stationName: 'Connaught Place SuperCharger',
    chargerId: 'c_001',
    chargerName: 'CP-001 · DC 150kW',
    startTime: new Date(Date.now() + 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() + 90 * 60 * 1000).toISOString(),
    estimatedKWh: 25,
    estimatedCost: 450,
    status: 'CONFIRMED',
    paymentStatus: 'PAID',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'b_002',
    stationId: 's_002',
    stationName: 'Cyber Hub FastCharge',
    chargerId: 'c_005',
    chargerName: 'CP-005 · DC 60kW',
    startTime: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 45 * 60 * 1000).toISOString(),
    estimatedKWh: 18,
    estimatedCost: 288,
    status: 'COMPLETED',
    paymentStatus: 'PAID',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'b_003',
    stationId: 's_004',
    stationName: 'Noida Sector 18 ChargeHub',
    chargerId: 'c_010',
    chargerName: 'CP-010 · DC 120kW',
    startTime: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000 + 60 * 60 * 1000).toISOString(),
    estimatedKWh: 32,
    estimatedCost: 544,
    status: 'COMPLETED',
    paymentStatus: 'PAID',
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

export const mockNotifications = [
  {
    id: 'n_1',
    type: 'booking',
    title: 'Booking confirmed',
    body: 'CP-001 reserved at 5:30 PM today.',
    ts: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    read: false,
  },
  {
    id: 'n_2',
    type: 'session',
    title: 'Session ended',
    body: 'Delivered 18.4 kWh · ₹294',
    ts: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    read: true,
  },
  {
    id: 'n_3',
    type: 'system',
    title: 'Welcome to ChargeFlow',
    body: 'Find chargers, book slots, and track sessions in real time.',
    ts: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    read: true,
  },
]
